stages:
  - install_dependencies
  - build
  - test

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

install_dependencies_frontend:
  stage: install_dependencies
  image: node:16
  script:
    - cd frontend
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
    paths:
      - node_modules/
  only:
    - master
    - eyy/ci-pipeline

install_dependencies_backend:
  stage: install_dependencies
  image: node:16
  script:
    - cd backend
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
    paths:
      - node_modules/
  only:
    - master
    - eyy/ci-pipeline

test_frontend:
  stage: test
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm test
  only:
    - master
    - eyy/ci-pipeline

test_backend:
  stage: test
  image: node:16
  script:
    - cd backend
    - npm ci
    - npm test
  only:
    - master
    - eyy/ci-pipeline
