stages:
  - install_dependencies
  - test

image: node:16

variables:
  JWT_SECRET: "your_jwt_secret_here" # Replace this with your actual JWT secret

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - backend/node_modules/

install_dependencies_frontend:
  stage: install_dependencies
  script:
    - cd frontend
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
  only:
    - master
    - eyy/ci-pipeline

install_dependencies_backend:
  stage: install_dependencies
  script:
    - cd backend
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
  only:
    - master
    - eyy/ci-pipeline

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm ci --prefer-offline
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend-test
  only:
    - master
    - eyy/ci-pipeline

test_backend:
  stage: test
  script:
    - cd backend
    - npm ci --prefer-offline
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend-test
  only:
    - master
    - eyy/ci-pipeline
