version: "3.8"
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  # depends_on:
  #   - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

volumes:
  db_data:
